//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiFaceRec.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-920FIQO\\SQLEXPRESS01;Initial Catalog=QuanLyRaVao;User ID=sa;P" +
            "assword=sa2012")]
        public string QuanLyRaVaoConnectionString {
            get {
                return ((string)(this["QuanLyRaVaoConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=congtackhac.serveftp.com;Initial Catalog=QuanLyRaVaoNhom2;User ID=sa;" +
            "Password=123456a@")]
        public string QuanLyRaVaoNhom2ConnectionString {
            get {
                return ((string)(this["QuanLyRaVaoNhom2ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=congtackhac.serveftp.com;Initial Catalog=QuanLyRaVao_Nhom2;User ID=sa" +
            ";Password=123456a@")]
        public string QuanLyRaVao_Nhom2ConnectionString {
            get {
                return ((string)(this["QuanLyRaVao_Nhom2ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-920FIQO\\SQLEXPRESS01;Initial Catalog=QuanLyRaVao_Nhom2;User I" +
            "D=sa;Password=sa2012")]
        public string QuanLyRaVao_Nhom2ConnectionString1 {
            get {
                return ((string)(this["QuanLyRaVao_Nhom2ConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=117.2.159.103,14333;Initial Catalog=QLyChungCu;User ID=sa;Password=sa" +
            "2012")]
        public string QLyChungCuConnectionString {
            get {
                return ((string)(this["QLyChungCuConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=117.2.159.103,14333;Initial Catalog=QLyChungCu;Persist Security Info=" +
            "True;User ID=sa;Password=sa2012")]
        public string QLyChungCuConnectionString1 {
            get {
                return ((string)(this["QLyChungCuConnectionString1"]));
            }
        }
    }
}
